USE [master]
GO

/****** Object:  Database [mean]    Script Date: 03.06.2020 13:22:09 ******/
CREATE DATABASE [mean]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'mean', FILENAME = N'C:\Users\oprid\mean.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'mean_log', FILENAME = N'C:\Users\oprid\mean_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [mean] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [mean].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [mean] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [mean] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [mean] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [mean] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [mean] SET ARITHABORT OFF 
GO

ALTER DATABASE [mean] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [mean] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [mean] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [mean] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [mean] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [mean] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [mean] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [mean] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [mean] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [mean] SET  DISABLE_BROKER 
GO

ALTER DATABASE [mean] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [mean] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [mean] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [mean] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [mean] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [mean] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [mean] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [mean] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [mean] SET  MULTI_USER 
GO

ALTER DATABASE [mean] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [mean] SET DB_CHAINING OFF 
GO

ALTER DATABASE [mean] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [mean] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [mean] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [mean] SET QUERY_STORE = OFF
GO

USE [mean]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [mean] SET  READ_WRITE 
GO


